### ISSUE TITLE
Unable to retrieve SDKs from oryx-cdn

### ISSUE THREAD

**Issue by Developer4190** [microsoft/Oryx#2443]
On build encountering an issue:

'Http request to retrieve the SDKs available to download from: 'https://oryx-cdn.microsoft.io' failed. 

This is happening for all function app and seems to be a new issue (within the last 2 weeks).

Please advise, this does not appear to be a firewall issue as I can ping the endpoint indicated ok.

**Comment by aderici** [comment]
In my case it was a B1 tier system, upgrading to a higher tier fixed the issue.

**Comment by mpwillia** [comment]
Same issue happened out of the blue. Deployments worked perfectly fine yesterday and today they stopped working. We've made no changes to our infrastructure. Has been working without problems for many months.
It's vnet integrated and our outbound NSG is wide open. We're running elastic premium EP1 app service plan & function app

- If I SSH to the function app through the portal I can curl https://oryx-cdn.microsoft.io/ without issue. 
- If I SSH to a devbox on the same vnet, it can curl https://oryx-cdn.microsoft.io/ without issue.
- Our function app is currently deployed with code that makes outbound networking calls just fine. These continue to run despite no new code being able to be built & deployed.
- Tried changing tiers and plans as @aderici suggested to no success.

**Comment by mpwillia** [comment]
> Same issue happened out of the blue. Deployments worked perfectly fine yesterday and today they stopped working. We've made no changes to our infrastructure. Has been working without problems for many months. It's vnet integrated and our outbound NSG is wide open. We're running elastic premium EP1 app service plan & function app
> 
> * If I SSH to the function app through the portal I can curl https://oryx-cdn.microsoft.io/ without issue.
> * If I SSH to a devbox on the same vnet, it can curl https://oryx-cdn.microsoft.io/ without issue.
> * Our function app is currently deployed with code that makes outbound networking calls just fine. These continue to run despite no new code being able to be built & deployed.
> * Tried changing tiers and plans as @aderici suggested to no success.

The issue appears resolved with no changes on my end, perhaps an issue on https://oryx-cdn.microsoft.io/ side?

**Comment by Developer4190** [comment]
This seems resolved for us. Closing.

**Comment by ShadowSonata** [comment]
I still have this issue (sorry I also commented on #2456) when deploying a node.js web app.

`Error: Oops... An unexpected error has occurred. Error: System.AggregateException: Http request to retrieve the SDKs available to download from 'https://oryx-cdn.microsoft.io' failed. Please ensure that your network configuration allows traffic to required Oryx dependencies, as documented in 'https://github.com/microsoft/Oryx/blob/main/doc/hosts/appservice.md#network-dependencies' System.AggregateException: One or more errors occurred. (A task was canceled.)`

Someone mentioned the B1 tier web app could be the issue but it was working before with the B1 tier web app. I also checked the network security group settings in the vnet it looks fine to me.

**Comment by aderici** [comment]
Faced this in a production tier app as well, it was p2 tier, changed to p3 and it worked

**Comment by ShadowSonata** [comment]
Thank you. I think in my case it was a NSG setting that I didn't notice has blocked Internet access. However, it seems I couldn't update NSG policy easily with service tags etc.
(See  #1585 )
